service:
  name: xdd-calendar-extract

custom:
  stage: ${opt:stage, self:provider.stage}
  kmsKeyArn: ${ssm:/xdd/security/kms-key-arn}
  storeBucketName: xdd-datalake-${self:custom.stage}.xebia.fr
  storeBucketKey: xke-calendar
  credentialKey: /xdd/security/google-service-account
  calendarIdKey: /xdd/calendar-extract/calendar-id

provider:
  name: aws
  runtime: java8
  region: eu-west-1
  logRetentionInDays: 14
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - "arn:aws:s3:::${self:custom.storeBucketName}/${self:custom.storeBucketKey}/*"
    - Effect: "Allow"
      Action:
        - "kms:Decrypt"
      Resource:
        - "${self:custom.kmsKeyArn}"
    - Effect: "Allow"
      Action:
        - "ssm:GetParameter"
      Resource:
        - 'Fn::Join':
          - ':'
          -
            - 'arn:aws:ssm'
            - Ref: 'AWS::Region'
            - Ref: 'AWS::AccountId'
            - 'parameter${self:custom.calendarIdKey}'
    - Effect: "Allow"
      Action:
        - "secretsmanager:GetSecretValue"
      Resource:
        - 'Fn::Join':
          - ':'
          -
            - 'arn:aws:secretsmanager'
            - Ref: 'AWS::Region'
            - Ref: 'AWS::AccountId'
            - 'secret:${self:custom.credentialKey}*'

package:
  artifact: build/distributions/calendar-extract.zip

functions:
  calendar-extract:
    handler: fr.xebia.api.xke.calendar.lambda.LambdaCalendarExtract
    timeout: 60
    events:
      - schedule: cron(0 8 * * ? *)
    environment:
      CALENDAR_ID_KEY: ${self:custom.calendarIdKey}
      CREDENTIAL_KEY: ${self:custom.credentialKey}
      STORE_BUCKET_NAME: ${self:custom.storeBucketName}
      STORE_BUCKET_KEY: ${self:custom.storeBucketKey}
    tags:
      Project: xdd
      Manager: Serverless
      Stage: ${self:custom.stage}
