service:
  name: xdd-xke-api-calendar-transform

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-plugin-existing-s3

custom:
  stage: ${opt:stage, self:provider.stage}
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: eu-west-1
  environment:
    XKE_BUCKET_NAME: ${self:custom.stage}-xdd-datalake.xebia.fr
    XKE_TABLE: ${self:custom.stage}-xdd-xke-api
    SLOTS_TO_EXCLUDE: 'XKE,Fondations,Déjeuner,New Comers,Notation Globale'
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 's3:GetObject'
      Resource:
        - 'arn:aws:s3:::${self:provider.environment.XKE_BUCKET_NAME}/*'
    - Effect: "Allow"
      Action:
        - 'dynamodb:Query'
        - 'dynamodb:Scan'
        - 'dynamodb:GetItem'
        - 'dynamodb:PutItem'
        - 'dynamodb:UpdateItem'
        - 'dynamodb:DeleteItem'
        - 'dynamodb:BatchGetItem'
        - 'dynamodb:BatchWriteItem'
      Resource:
        - 'arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.XKE_TABLE}'

functions:
  calendar-transform:
    handler: handler.handler
    events:
      - existingS3:
          bucket: ${self:provider.environment.XKE_BUCKET_NAME}
          events:
            - s3:ObjectCreated:*
          rules:
            - prefix: xke-calendar/
            - suffix: .json

resources:
  Resources:
  #For poc the table is create there but
  #we think is not the responsibility of the transformer to do it
    XkeDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
#      DeletionPolicy: Retain
      Properties:
        TableName: ${self:provider.environment.XKE_TABLE}
        AttributeDefinitions:
          - AttributeName: 'year'
            AttributeType: 'S'
          - AttributeName: 'month'
            AttributeType: 'S'
        KeySchema:
          - AttributeName: 'year'
            KeyType: 'HASH'
          - AttributeName: 'month'
            KeyType: 'RANGE'
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
