service: xdd-api-authorizer

custom:
  stage: ${opt:stage, self:provider.stage}
  audience:
    dev: https://api.techx.fr
    prod: https://api.xebia.fr

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1
  logRetentionInDays: 14

functions:
  authorizer:
    handler: handler.authenticate
    environment:
      AUDIENCE: ${self:custom.audience.${self:custom.stage}}
      JWKS_URI: https://xdd.eu.auth0.com/.well-known/jwks.json
      TOKEN_ISSUER: https://xdd.eu.auth0.com/
    tags:
      Project: xdd
      Manager: Serverless
      Stage: ${self:custom.stage}
