version: 2

jobs:
  test_calendar_extract:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "~/project/calendar-extract/build.gradle" }}
            - gradle
      - run: ~/project/calendar-extract/gradlew test
      - save_cache:
          key: gradle-{{ checksum "~/project/calendar-extract/build.gradle" }}
          paths:
            - ~/.gradle
      - store_test_results:
          path: ~/project/calendar-extract/build/test-results

workflows:
  version: 2
  tests:
    jobs:
      - test_calendar_extract
