service:
  name: xdd-blog-posts

custom:
  stage: ${opt:stage, self:provider.stage}
  kmsKeyArn: ${ssm:/xdd/security/kms-key-arn}
  storeBucketName: xdd-datalake-${self:custom.stage}.xebia.fr
  storeBucketKey: raw/blog-posts

provider:
  name: aws
  runtime: java8
  region: eu-west-1
  logRetentionInDays: 14
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - "arn:aws:s3:::${self:custom.storeBucketName}/${self:custom.storeBucketKey}/*"
    - Effect: "Allow"
      Action:
        - "kms:Decrypt"
      Resource:
        - "${self:custom.kmsKeyArn}"

package:
  artifact: build/distributions/posts-extract.zip

functions:
  extract:
    handler: fr.xebia.blog.extract.lambda.LambdaBlogPostsExtract
    timeout: 60
    events:
      - schedule: cron(0 8 * * ? *)
    environment:
      STORE_BUCKET_NAME: ${self:custom.storeBucketName}
      STORE_BUCKET_KEY: ${self:custom.storeBucketKey}
    tags:
      Project: xdd
      Manager: Serverless
      Stage: ${self:custom.stage}
