service:
  name: xdd-hr-extract

custom:
  stage: ${opt:stage, self:provider.stage}
  kmsKeyArn: ${ssm:/xdd/security/kms-key-arn}
  serviceAccountKey: /xdd/security/google-service-account
  sheetIdKey: /xdd/hr-sheet/sheet-id
  sheetRangeKey: /xdd/hr-sheet/sheet-range
  storeBucketName: xdd-datalake-${self:custom.stage}.xebia.fr
  storeBucketKey: hr-sheet

provider:
  name: aws
  runtime: java8
  region: eu-west-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - "arn:aws:s3:::${self:custom.storeBucketName}/${self:custom.storeBucketKey}/*"
    - Effect: "Allow"
      Action:
        - "kms:Decrypt"
      Resource:
        - "${self:custom.kmsKeyArn}"
    - Effect: "Allow"
      Action:
        - "ssm:GetParameter"
      Resource:
        - 'Fn::Join':
          - ':'
          -
            - 'arn:aws:ssm'
            - Ref: 'AWS::Region'
            - Ref: 'AWS::AccountId'
            - 'parameter${self:custom.sheetIdKey}'
        - 'Fn::Join':
          - ':'
          -
            - 'arn:aws:ssm'
            - Ref: 'AWS::Region'
            - Ref: 'AWS::AccountId'
            - 'parameter${self:custom.sheetRangeKey}'
    - Effect: "Allow"
      Action:
        - "secretsmanager:GetSecretValue"
      Resource:
        - 'Fn::Join':
          - ':'
          -
            - 'arn:aws:secretsmanager'
            - Ref: 'AWS::Region'
            - Ref: 'AWS::AccountId'
            - 'secret:${self:custom.serviceAccountKey}*'

package:
  artifact: build/distributions/hr-extract.zip

functions:
  hr-extract:
    handler: fr.xebia.hr.extract.lambda.LambdaHRExtract
    timeout: 60
    events:
      - schedule: cron(0 8 * * ? *)
    environment:
      SERVICE_ACCOUNT_KEY: ${self:custom.serviceAccountKey}
      SHEET_ID_KEY: ${self:custom.sheetIdKey}
      SHEET_RANGE_KEY: ${self:custom.sheetRangeKey}
      STORE_BUCKET_NAME: ${self:custom.storeBucketName}
      STORE_BUCKET_KEY: ${self:custom.storeBucketKey}
    tags:
      Project: xdd
      Manager: Serverless
      Stage: ${self:custom.stage}
