service:
  name: xdd-picture-drive

custom:
  stage: ${opt:stage, self:provider.stage}
  kmsKeyArn: ${ssm:/xdd/security/kms-key-arn}
  serviceAccountKey: /xdd/security/google-service-account
  parentFolderIdKey: /xdd/picture-drive/parent-folder-id
  topicName: ${self:service.name}-${self:custom.stage}
  storeBucketName: xdd-datalake-${self:custom.stage}.xebia.fr
  storeBucketKey: raw/picture-drive

provider:
  name: aws
  runtime: java8
  region: eu-west-1
  logRetentionInDays: 14
  environment:
    SERVICE_ACCOUNT_KEY: /xdd/security/google-service-account
    PARENT_FOLDER_ID_KEY: ${self:custom.parentFolderIdKey}
    MIME_TYPE: "image/jpeg"
    PAGE_SIZE: "200"
    STORE_BUCKET_NAME: ${self:custom.storeBucketName}
    STORE_BUCKET_KEY: ${self:custom.storeBucketKey}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - "arn:aws:s3:::${self:custom.storeBucketName}/${self:custom.storeBucketKey}/*"
    - Effect: "Allow"
      Action:
        - "kms:Decrypt"
      Resource:
        - "${self:custom.kmsKeyArn}"
    - Effect: "Allow"
      Action:
        - "sns:*"
      Resource:
        - Fn::Join: [ ":", ["arn:aws:sns", Ref: "AWS::Region", Ref: "AWS::AccountId", "${self:custom.topicName}" ] ]
    - Effect: "Allow"
      Action:
        - "ssm:GetParameter"
      Resource:
        - Fn::Join: [ ":", [ "arn:aws:ssm", Ref: "AWS::Region", Ref: "AWS::AccountId", "parameter${self:custom.parentFolderIdKey}" ] ]
    - Effect: "Allow"
      Action:
        - "secretsmanager:GetSecretValue"
      Resource:
        - Fn::Join: [ ":", [ "arn:aws:secretsmanager", Ref: "AWS::Region", Ref: "AWS::AccountId", "secret:${self:custom.serviceAccountKey}*" ] ]

package:
  artifact: build/distributions/picture-extract.zip

functions:
  extract:
    handler: fr.xebia.picture.extract.lambda.LambdaPictureExtract
    timeout: 240
    events:
      - schedule: cron(0 8 * * ? *)
    environment:
      TOPIC_ARN: { Fn::Join: [ ":", [ "arn:aws:sns", Ref: "AWS::Region", Ref: "AWS::AccountId", "${self:custom.topicName}" ] ] }
    tags:
      Project: xdd
      Manager: Serverless
      Stage: ${self:custom.stage}
  store:
    handler: fr.xebia.picture.extract.lambda.LambdaPictureListener
    timeout: 240
    events:
      - sns:
          topicName: ${self:custom.topicName}
          displayName: "Topic for picture extraction"
    reservedConcurrency: 5
    tags:
      Project: xdd
      Manager: Serverless
      Stage: ${self:custom.stage}
