FORMAT: 1A

# XKE

XKE is Xebia API allowing users to make search about xke events

# XKE Events

Resources related to xke in the API.

## find one Xke  [/xke/{year}/{month}]
### List All Presentation of this specific xke [GET]

+ Parameters
    + year: 2018 (string, required) - year of the xke
    + month: 02 (string, required) - month of the xke

+ Response 200 (application/json)
    + Body

            [
               {
                     "year": "2018",
                     "month": "02",
                     "level": "Intermédiaire",
                     "logistics": "Slot filmé si possible",
                     "pitch": "Apache Kafka et sa librairie de *stream processing*",
                     "requirement": "Pouvoir lire du code Java (attention aux allergiques)"
               }, {
                     "year": "2018",
                     "month": "02",
                     "level": "Intermédiaire",
                     "logistics": "RAS",
                     "pitch": "Tout le monde a entendu parler d'HTTP2, mais qu'est-ce qu'il se cache derrière cet acronyme ?\nDécouvrez ce qu'apporte ce nouveau protocole au travers d'exemples d'implémentation en NodeJS.",
                     "requirement": "Javascript"
                }
            ]
