service: xdd-xke-api

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-plugin-existing-s3

custom:
  region: ${opt:region, self:provider.region}
  stage: ${opt:stage, self:provider.stage}
  perEnv: ${file(serverless-config-environment.yml):${self:custom.stage}, file(serverless-config-environment.yml):dev}
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

  customDomain:
    basePath: "${self:custom.perEnv.basePath}"
    domainName: "${self:custom.perEnv.domainName}"
    stage: "${self:custom.stage}"
    createRoute53Record: true

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: eu-west-1
  environment:
    XKE_BUCKET_NAME: ${self:custom.stage}-xdd-datalake.xebia.fr
    XKE_TABLE: ${self:custom.stage}-xdd-xke-api
    SLOTS_TO_EXCLUDE: 'XKE,Fondations,Déjeuner,New Comers,Notation Globale,Pitchs,Plénière'
    ENDPOINT_URL:
      "Fn::Join":
        - ""
        -
          - "https://"
          - "${self:custom.perEnv.domainName}"
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 's3:GetObject'
      Resource:
        - 'arn:aws:s3:::${self:provider.environment.XKE_BUCKET_NAME}/*'
    - Effect: "Allow"
      Action:
        - 'dynamodb:Query'
        - 'dynamodb:Scan'
        - 'dynamodb:GetItem'
        - 'dynamodb:BatchGetItem'
        - 'dynamodb:PutItem'
        - 'dynamodb:UpdateItem'
        - 'dynamodb:DeleteItem'
        - 'dynamodb:BatchWriteItem'
      Resource:
        - 'arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.XKE_TABLE}'

functions:
  find-one:
    handler: handler.findXke
    warmup: true
    events:
      - http:
          path: /{year}
          method: GET
          cors: true
      - http:
          path: /{year}/{month}
          method: GET
          cors: true
  calendar-transform:
    handler: handler.transform
    events:
      - existingS3:
          bucket: ${self:provider.environment.XKE_BUCKET_NAME}
          events:
            - s3:ObjectCreated:*
          rules:
            - prefix: xke-calendar/
            - suffix: .json

resources:
  Resources:
    XkeDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: ${self:provider.environment.XKE_TABLE}
        AttributeDefinitions:
          - AttributeName: 'year'
            AttributeType: 'S'
          - AttributeName: 'month'
            AttributeType: 'S'
        KeySchema:
          - AttributeName: 'year'
            KeyType: 'HASH'
          - AttributeName: 'month'
            KeyType: 'RANGE'
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

