service: xdd-xke-api

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-plugin-existing-s3

custom:
  region: ${opt:region, self:provider.region}
  stage: ${opt:stage, self:provider.stage}
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1
  logRetentionInDays: 14
  environment:
    XKE_BUCKET_DATA: xdd-datalake-${self:custom.stage}.xebia.fr
    XKE_TABLE: xdd-xke-api-${self:custom.stage}
    XKE_BUCKET_API: xdd-xke-api-${self:custom.stage}.xebia.fr
    SLOTS_TO_EXCLUDE: 'XKE,Fondations,Déjeuner,New Comers,Notation Globale,Pitchs,Plénière'
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 's3:GetObject'
      Resource:
        - 'arn:aws:s3:::${self:provider.environment.XKE_BUCKET_DATA}/*'
    - Effect: 'Allow'
      Action:
        - 's3:GetObject'
        - 's3:PutObject'
        - 's3:ListBucket'
      Resource:
        - 'arn:aws:s3:::${self:provider.environment.XKE_BUCKET_API}/*'
    - Effect: 'Allow'
      Action:
        - 's3:ListBucket'
      Resource:
        - 'arn:aws:s3:::*'

functions:
  calendar-transform:
    handler: handler.transform
    events:
      - existingS3:
          bucket: ${self:provider.environment.XKE_BUCKET_DATA}
          events:
            - s3:ObjectCreated:*
          rules:
            - prefix: raw/xke-calendar/
            - suffix: .json
    tags:
      Project: xdd
      Manager: Serverless
      Stage: ${self:custom.stage}
  find-one:
    handler: handler.findXke
    warmup: true
    timeout: 30
    events:
      - http:
          path: /{year}/{month}
          method: GET
          cors: true
          authorizer:
            arn: ${cf:xdd-api-authorizer-${self:custom.stage}.AuthorizerLambdaFunctionQualifiedArn}
            resultTtlInSeconds: 0
            identitySource: method.request.header.X-Authorization
    tags:
      Project: xdd
      Manager: Serverless
      Stage: ${self:custom.stage}

resources:
  Resources:
    XkeBucketApi:
      Type: 'AWS::S3::Bucket'
      DeletionPolicy: Retain
      Properties:
        BucketName: ${self:provider.environment.XKE_BUCKET_API}
        AccessControl: Private
        Tags:
          -
            Key: Project
            Value: xdd
